### ISSUE TITLE
Config File Loading

### ISSUE THREAD

**Issue by Ry0511** [bl-sdk/pyunrealsdk#56]
Preface: This is about changes which are 'upcoming' so very likely these are things you are aware of already.

When loading the config files if the file does not exist it will always print a stacktrace regardless of if the file is optional or not (which I assume `unrealsdk.user.toml` is). Another issue is that input to the lambda is `const T&&` which is probably supposed to be `const T&`

see `./src/pyunrealsdk/base_bindings.cpp` at `void create_and_add_config_dict(pybind11::module_ &mod)`

```c++
                               /* Supposed to be const T& ? */
    auto load_config_file = [](const std::filesystem::path&& path) -> py::object {
        try {
            const py::dict globals{"path"_a = path};
            py::exec(
                "import tomllib\n"
                "with path.open(\"rb\") as file:\n"
                "    config = tomllib.load(file)\n",
                globals);
            return globals["config"];

        } catch (const std::exception& ex) {
            /* Stack trace & Error here if the file doesn't exist might confuse users */
            LOG(ERROR, "Failed to load {}", path.string());
            logging::log_python_exception(ex);
            return py::none{};
        }
    };
```

**Comment by apple1417** [comment]
fwiw taking an rvalue reference is correct because of how the lambda is called bellow
```cpp
auto base_config = load_config_file(unrealsdk::config::get_base_config_file_path());
auto user_config = load_config_file(unrealsdk::config::get_user_config_file_path());
```

The paths returned by `get_*_config_path` are just temporaries, since they're not needed elsewhere in the function, so they don't have an address for a regular reference to take. It also means the paths are moved, so even at -O1 it just becomes some register shuffling once compiled ([godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:16,positionColumn:2,positionLineNumber:16,selectionStartColumn:2,selectionStartLineNumber:16,startColumn:2,startLineNumber:16),source:'//+Type+your+code+here,+or+load+an+example.%0A%23include+%3Cfilesystem%3E%0A%0Astd::filesystem::path+get_base_config_file_path(void)%3B%0Astd::filesystem::path+get_user_config_file_path(void)%3B%0Avoid+do_something_with_path(const+std::filesystem::path%26)%3B%0A%0Avoid+create_and_add_config_dict(void)%0A%7B%0A++++auto+load_config_file+%3D+%5B%5D(const+std::filesystem::path%26%26+path)+%7B%0A++++++++do_something_with_path(path)%3B%0A++++%7D%3B%0A%0A++++load_config_file(get_base_config_file_path())%3B%0A++++load_config_file(get_user_config_file_path())%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O1',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+(trunk)+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)).

**Comment by Ry0511** [comment]
hmm, interesting i've only ever used rvalues for move semantics and just assumed you had to use a `const T&` since it will expand the lifetime of the variable. Seems that rvalues can bind to rvalues in the same way they can bind to `const lvalue&` extending the lifetime in the sameway; cool.

[cppref-rvalue](https://en.cppreference.com/w/cpp/language/value_category#rvalue)
